### ISSUE TITLE
iOS 8 support

### ISSUE THREAD

**Issue by dclerc** [iZettle/sdk-ios#120]
The ReadMe file says the SDK works with iOS 8 but when our clients first installed our app this morning on iOS 8 devices they got a crash with the following message:
dyld: Symbol not found: ___NSArray0__ ... Frameworks/iZettleShared.framework/iZettleShared (which was built for iOS 9.0)

We have to revert back to 1.3.x urgently because of this. Please provide us with a version of the SDK that works with iOS 8 ASAP!

**Comment by mansbernhardt** [comment]
That was really unfortunate. It seems the information about the crash you provided has been cut off. If you could provide us with a more complete crash report that would be of great help. 

/Måns

Sent from my iPhone

> 11 feb. 2017 kl. 09:40 skrev dclerc <notifications@github.com>:
> 
> message:

**Comment by dclerc** [comment]
If you run your sample app in an iOS 8 simulator you'll get the same error message in XCode.

**Comment by mansbernhardt** [comment]
@dclerc We are working on a 1.4.2 build that should become available later today.

**Comment by dclerc** [comment]
I've just tested the 1.4.2b build with iOS 8 and can confirm it works fine.

**Comment by Sajjon** [comment]
@dclerc Hello! Alex from iZettle here. We are sorry for the inconvenience with the accidental iOS 8 support drop.

Great that `1.4.2b` beta branch worked. We have just released `1.4.2` publicly, available through Cocoapods and also here: https://github.com/iZettle/sdk-ios/releases/tag/1.4.2

So I just deleted the beta branch (`1.4.2b`).

Thank you for opening this issue, I will close it now.
